// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalApi.Data;

#nullable disable

namespace PersonalAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241111225925_MigracaoViolino")]
    partial class MigracaoViolino
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonalApi.Models.Acessorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Materiais")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("TipoAcessorios")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.Property<int?>("ViolinoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ViolinoId");

                    b.ToTable("TB_ACESSORIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "As cordas Mauro Calixto são indicadas para qualquer estilo musical e procuradas iniciantes...",
                            Marca = "Mauro Calixto",
                            Materiais = "Núcleo de fibra sintética e Revestimento em aço",
                            Modelo = "Padrão",
                            Nome = "Encordeamento",
                            TipoAcessorios = 1,
                            Valor = 52.0,
                            ViolinoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Produzido na Alemanha se utilizando dos melhores materiais, a marca Pirastro é dominante no sergmento de...",
                            Marca = "Pirastro",
                            Materiais = "Resina Natural de Pinho",
                            Modelo = "CV-52",
                            Nome = "Breu",
                            TipoAcessorios = 2,
                            Valor = 54.649999999999999,
                            ViolinoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "A espaleira Lunnon new apresenta design mais anatômico, que proporciona conforto, segurança e flexibilidade...",
                            Marca = "Lunnon",
                            Materiais = "Plástico injetável",
                            Modelo = "New",
                            Nome = "Espaleira",
                            TipoAcessorios = 3,
                            Valor = 36.0,
                            ViolinoId = 1
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Produto Original da Fábrica, é necessário fazer furos e ajustes em um Luthier para que seja regulado em seu instrumento...",
                            Marca = " NETO VIOLINOS",
                            Materiais = "ÉBANO MESCLADO",
                            Modelo = "KIT 04 CRAVELHAS TAMARINDO PREMIUM",
                            Nome = "Cravelha",
                            TipoAcessorios = 4,
                            Valor = 48.950000000000003,
                            ViolinoId = 1
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Também pode ser chamado simplesmente de fixo, é uma peça que utilizamos para ajudar no momento de afinação...",
                            Marca = "Mavis",
                            Materiais = "Metal",
                            Modelo = "Niquelado",
                            Nome = "Microafinador",
                            TipoAcessorios = 5,
                            Valor = 9.3599999999999994,
                            ViolinoId = 1
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "A queixeira é um acessório que se encaixa no extremo do corpo do violino ou da viola de arco. É um peça essencial...",
                            Marca = "Mavis",
                            Materiais = "Madeira de Ébano",
                            Modelo = "Ébano",
                            Nome = "Queixeira",
                            TipoAcessorios = 6,
                            Valor = 84.200000000000003,
                            ViolinoId = 1
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Disponíveis nos tamanhos:  1/10, 1/16, 1/4, 1/2, 3/4 e 4/4...",
                            Marca = "Mavis",
                            Materiais = "Madeira de Ébano",
                            Modelo = "Ébano",
                            Nome = "Estandarte",
                            TipoAcessorios = 7,
                            Valor = 50.939999999999998,
                            ViolinoId = 1
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Cavalete fabricado com madeira Maple de ótima qualidade, com a finalidade de proporcionar ao músico uma maior precisão...",
                            Marca = "Mavis",
                            Materiais = "Madeira Mapple",
                            Modelo = "Madeira Mapple Mavis",
                            Nome = "Cavalete",
                            TipoAcessorios = 8,
                            Valor = 12.470000000000001,
                            ViolinoId = 1
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Descubra a qualidade excepcional do Arco Para Violino Eagle 4/4 VWB-44R Crina Animal Natural...",
                            Marca = "Eagle",
                            Materiais = "Hardwood no formato Octogonal (oitavado), Crina animal natural, Talão de ébano com madre-pérola Olho París incrustada",
                            Modelo = "VWB44R",
                            Nome = "Arco",
                            TipoAcessorios = 9,
                            Valor = 89.099999999999994,
                            ViolinoId = 1
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "Disponíveis nos tamanhos: 1/16, 1/8, 1/4, 1/2 e 3/4...",
                            Marca = "Mavis",
                            Materiais = "Madeira de Ébano",
                            Modelo = "Ébano",
                            Nome = "Espelho",
                            TipoAcessorios = 10,
                            Valor = 90.439999999999998,
                            ViolinoId = 1
                        });
                });

            modelBuilder.Entity("PersonalApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAcesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_USUARIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "seuEmail@gmail.com",
                            Latitude = -23.520024100000001,
                            Longitude = -46.596497999999997,
                            PasswordHash = new byte[] { 66, 252, 228, 64, 123, 188, 137, 246, 160, 63, 168, 155, 51, 254, 130, 35, 77, 0, 182, 177, 234, 138, 159, 123, 109, 14, 27, 12, 95, 172, 174, 77, 158, 180, 28, 214, 33, 234, 66, 236, 177, 195, 198, 255, 153, 180, 252, 125, 17, 230, 89, 87, 97, 129, 121, 216, 106, 240, 0, 175, 106, 15, 41, 185 },
                            PasswordSalt = new byte[] { 228, 63, 68, 129, 62, 83, 58, 140, 1, 101, 182, 139, 180, 209, 76, 215, 84, 251, 60, 71, 71, 230, 191, 103, 204, 96, 239, 129, 147, 78, 62, 14, 186, 78, 203, 75, 186, 166, 130, 186, 231, 73, 216, 1, 80, 89, 97, 154, 188, 87, 113, 252, 74, 173, 62, 36, 92, 109, 51, 215, 160, 142, 35, 4, 113, 162, 30, 48, 144, 185, 189, 7, 190, 14, 4, 9, 148, 200, 159, 112, 204, 140, 221, 192, 86, 55, 3, 214, 183, 42, 177, 77, 145, 60, 152, 222, 3, 242, 182, 240, 35, 31, 26, 14, 218, 161, 231, 64, 223, 147, 54, 111, 225, 240, 242, 68, 19, 148, 197, 48, 94, 228, 105, 250, 111, 160, 229, 43 },
                            Perfil = "Admin",
                            Username = "UsuarioAdmin"
                        });
                });

            modelBuilder.Entity("PersonalApi.Models.Violino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Materiais")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_VIOLINOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Queixeira, estandarte, cravelhas e botão: Ébano. Encordoamento: M Calixto. Arco de crina natural e madeira maçaranduba. Estojo Gota. Ajuste Profissional (cavalete original, alma, pestana, cravelhas)",
                            Marca = "Eagles",
                            Materiais = "Violino: Abeto e Atiro. Ébano. Arco: Maçaranduba",
                            Modelo = "CV-12",
                            UsuarioId = 1,
                            Valor = 1283.8499999999999
                        });
                });

            modelBuilder.Entity("PersonalApi.Models.Acessorio", b =>
                {
                    b.HasOne("PersonalApi.Models.Violino", "Violino")
                        .WithMany("Acessorios")
                        .HasForeignKey("ViolinoId");

                    b.Navigation("Violino");
                });

            modelBuilder.Entity("PersonalApi.Models.Violino", b =>
                {
                    b.HasOne("PersonalApi.Models.Usuario", "Usuario")
                        .WithMany("Violinos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PersonalApi.Models.Usuario", b =>
                {
                    b.Navigation("Violinos");
                });

            modelBuilder.Entity("PersonalApi.Models.Violino", b =>
                {
                    b.Navigation("Acessorios");
                });
#pragma warning restore 612, 618
        }
    }
}
